# Generated by Django 3.0.1 on 2019-12-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'posts'},
        ),
    ]
